### ISSUE TITLE
internal links extraction

### ISSUE THREAD

**Issue by Panithecracker** [jjelwood/wikimap#2]
#!/usr/bin/python3

#this file retrieves the internal links of different article names
import requests

S = requests.Session()

URL = "https://en.wikipedia.org/w/api.php" #general api url link

# for each article, based on its title, use the active session to fetch via the wikipedia api the internal links titles
articles_titles = ["Albert Einstein", "Penélope Cruz", "Eric Clapton"] #the idea is that you modify this so that the ones already in sql are given as a list here
for t in articles_titles:
    print("Internal links from the article about "+t)
    print("\n")
    PARAMS = {
        "action": "query",
        "format": "json",
        "titles": t,
        "prop": "links"
    }
    R = S.get(url=URL, params=PARAMS)
    DATA = R.json()

    PAGES = DATA["query"]["pages"]

    for k, v in PAGES.items():
        for l in v["links"]:
            print(l["title"])

**Comment by jjelwood** [comment]
Added in `get_links.py`
